hello/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import register_view, UserDetailView, UserList, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('list/', UserList.as_view(), name='user-list'),
    path('profile/change/', UserChangeView.as_view(), name='user-change'),
    path('change-password/', UserPasswordChangeView.as_view(), name='user-password-change')
]

hello/hello/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

HOMEPAGE_URL = 'webapp/'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url=HOMEPAGE_URL, permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hello/webapp/urls.py
from django.urls import path
from webapp.views import (
    IndexView,
    TaskView,
    CreateTask,
    UpdateTask,
    DeleteTask,
    ProjectView,
    ProjectDetailView,
    ProjectCreate,
    ProjectUpdate,
    ProjectDelete,
    AddUser

)

app_name = 'project'

urlpatterns = [
    path('tracker/', IndexView.as_view(), name='list-task'),
    path('<int:pk>/tracker/view/', TaskView.as_view(), name='view-task'),
    path('<int:pk>/tracker/add/', CreateTask.as_view(), name='add-task'),
    path('<int:pk>/tracker/update/', UpdateTask.as_view(), name='update-task'),
    path('<int:pk>/tracker/delete/', DeleteTask.as_view(), name='delete-task'),
    path('', ProjectView.as_view(), name='list'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='view'),
    path('add/', ProjectCreate.as_view(), name='add'),
    path('<int:pk>/update/', ProjectUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', ProjectDelete.as_view(), name='delete'),
    path('project/add/<int:pk>/', AddUser.as_view(), name='add-user'),
    # path('<int:pk>/project/delete/', DeleteUser.as_view(), name='delete-user'),
]

hello/webapp/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth import get_user_model


# Create your models here.


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Status(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'статус'
        verbose_name_plural = 'статусы'

class Type(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, verbose_name='Тип')

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'тип'
        verbose_name_plural = 'типы'


class Task(BaseModel):
    summary = models.CharField(max_length=200, null=False, blank=False, verbose_name='Заголовок', validators=[MinLengthValidator(5), ])
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание', validators=[MinLengthValidator(10), ])
    status = models.ForeignKey('webapp.Status', on_delete=models.PROTECT, related_name='tasks', null=False, blank=False)
    type = models.ManyToManyField('webapp.Type', related_name='tasks', blank=False)
    project = models.ForeignKey(
        'webapp.Project',
        on_delete=models.CASCADE,
        related_name='tasks',
        null=False,
        blank=False,
        default=1
    )
    class Meta:
        db_table = 'Tasks'
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return f'{self.id}. {self.summary}: {self.description}'


class Project(BaseModel):
    name = models.CharField(max_length=200, null=False, blank=False, verbose_name='Название')
    description_project = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание проекта')
    start_date = models.DateField(null=False, blank=False)
    end_date = models.DateField(null=True, blank=True)
    user = models.ManyToManyField(get_user_model(), related_name='projects', null=False, blank=False, verbose_name='Пользователь')

    class Meta:
        db_table = 'Projects'
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'
        permissions = [
            ('have_user', 'есть пользователь')
        ]

    def __str__(self):
        return f'{self.id}: {self.name} {self.description_project}'

hello/webapp/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import TemplateView, FormView, ListView
from django.urls import reverse
from django.db.models import Q
from django.utils.http import urlencode

from webapp.models import Task
from webapp.form import TaskForm, SearchForm
from webapp.base_views import CustomFormView
# Create your views here.



class IndexView(ListView):
    template_name = 'index.html'
    model = Task
    context_object_name = 'tasks'
    ordering = ('summary', '-created_at')
    paginate_by = 10
    paginate_orphans = 1

    def get(self, request, **kwargs):
        self.form = SearchForm(request.GET)
        self.search_data = self.get_search_data()
        return super(IndexView, self).get(request, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.search_data:
            queryset = queryset.filter(
                Q(summary__icontains=self.search_data) |
                Q(description__icontains=self.search_data)
            )
        return queryset

    def get_search_data(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search_value']
        return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.form

        if self.search_data:
            context['query'] = urlencode({'search_value': self.search_data})
        return context


class TaskView(TemplateView):

    template_name = 'task_view.html'

    def get_context_data(self, **kwargs):
        kwargs['task'] = get_object_or_404(Task, id=kwargs.get('pk'))
        return super().get_context_data(**kwargs)


class CreateTask(CustomFormView):
    template_name = 'task_create.html'
    form_class = TaskForm
    redirect_url = 'list-task'

    def form_valid(self, form):
        type = form.cleaned_data.pop('type')
        task = Task()
        for key, value in form.cleaned_data.items():
            setattr(task, key, value)

        task.save()
        task.type.set(type)

        return super().form_valid(form)

class UpdateTask(FormView):
    template_name = 'task_update.html'
    form_class = TaskForm

    def dispatch(self, request, *args, **kwargs):
        self.task = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = self.task
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.task
        return kwargs

    def form_valid(self, form):
        self.task = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('view-task', kwargs={'pk': self.task.pk})

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Task, pk=pk)


class DeleteTask(TemplateView):
    template_name = 'task_delete.html'

    def get_context_data(self, **kwargs):
        kwargs['task'] = get_object_or_404(Task, id=kwargs.get('pk'))
        return super().get_context_data(**kwargs)

    def post(self, request, **kwargs):
        task = get_object_or_404(Task, pk=kwargs.get('pk'))
        task.delete()
        return redirect('list-task')

hello/webapp/views/project.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from webapp.models import Project, Task
from webapp.form import ProjectForm, ProjectUserForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied


class ProjectView(ListView):
    template_name = 'project/project.html'
    model = Project
    context_object_name = 'projects'
    paginate_by = 10
    paginate_orphans = 1



class ProjectDetailView(DetailView):
    template_name = 'project/project_detail.html'
    context_key = 'project'
    model = Project


class ProjectCreate(PermissionRequiredMixin, CreateView):
    template_name = 'project/project_create.html'
    form_class = ProjectForm
    model = Project
    permission_required = 'webapp.add_project'

    def get_success_url(self):
        return reverse(
            'project:view',
            kwargs={'pk': self.object.pk}
        )


class ProjectUpdate(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'project/project_update.html'
    form_class = ProjectForm
    context_key = 'project'
    permission_required = 'webapp.change_project'
    def get_success_url(self):
        return reverse(
            'project:view',
            kwargs={'pk': self.object.pk}
        )



class ProjectDelete(PermissionRequiredMixin, DeleteView):
    template_name = 'project/project_delete.html'
    model = Project
    context_key = 'project'
    success_url = reverse_lazy('project:list')
    permission_required = 'webapp.delete_project'




class AddUser(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'user/user_create.html'
    form_class = ProjectUserForm
    context_object_name = 'project'
    permission_required = 'webapp.have_user'

    def get_success_url(self):
        return reverse(
            'project:view',
            kwargs={'pk': self.object.pk}
        )

    def has_permission(self):
        return super().has_permission() and self.request.user in Project.objects.get(
        pk=self.kwargs.get('pk')).user.all()

hello/webapp/views/trackers.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, FormView, ListView, CreateView, TemplateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from django.utils.http import urlencode
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from webapp.models import Task, Project
from webapp.form import TaskForm, SearchForm
from webapp.base_views import CustomFormView
# Create your views here.



class IndexView(ListView):
    template_name = 'tracker/index.html'
    model = Task
    context_object_name = 'tasks'
    ordering = ('summary', '-created_at')
    paginate_by = 10
    paginate_orphans = 1

    def get(self, request, **kwargs):
        self.form = SearchForm(request.GET)
        self.search_data = self.get_search_data()
        return super(IndexView, self).get(request, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.search_data:
            queryset = queryset.filter(
                Q(summary__icontains=self.search_data) |
                Q(description__icontains=self.search_data)
            )
        return queryset

    def get_search_data(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search_value']
        return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.form

        if self.search_data:
            context['query'] = urlencode({'search_value': self.search_data})
        return context


class TaskView(DetailView):
    model = Task
    template_name = 'tracker/task_view.html'



class CreateTask(PermissionRequiredMixin, CreateView):
    template_name = 'tracker/task_create.html'
    form_class = TaskForm
    model = Task
    permission_required = 'webapp.add_task'

    def form_valid(self, form):
        project = get_object_or_404(Project, id=self.kwargs.get('pk'))
        task = form.save(commit=False)
        task.project = project
        task.save()
        form.save_m2m()
        return redirect(reverse('project:view', kwargs={'pk': project.pk}))

    def has_permission(self):
        return super().has_permission() and self.request.user in Project.objects.get(
            pk=self.kwargs.get('pk')).user.all()



class UpdateTask(PermissionRequiredMixin, UpdateView):
    model = Task
    template_name = 'tracker/task_update.html'
    form_class = TaskForm
    context_object_name = 'task'
    permission_required = 'webapp.change_task'

    def get_success_url(self):
        return reverse('project:view-task', kwargs={'pk': self.kwargs.get('pk')})

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().project.user.all()



class DeleteTask(PermissionRequiredMixin, DeleteView):
    model = Task
    template_name = 'tracker/task_delete.html'
    context_object_name = 'task'
    success_url = reverse_lazy('project:list-task')
    permission_required = 'webapp.delete_task'

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().project.user.all()

hello/webapp/templates/project/project.html
{% extends 'base.html' %}

{% block menu %}
    {% if perms.webapp.add_project %}
         <li><a href="{% url "project:add" %}">Create project</a></li>
    {% endif %}
    {% if perms.accounts.view_user %}
        <li><a href="{% url "accounts:user-list" %}">Пользователь</a></li>
    {% endif %}
{% endblock menu %}
{% block title %}Project{% endblock title %}
{% block page_header %}Все проекты{% endblock page_header %}

{% block content %}
    {% if not projects %}
        <h2>НЕТ проектов</h2>
        {% else %}

    {% endif %}
{#        <table class="table">#}
{#          <thead>#}
{#            <tr>#}
{#              <th scope="col">Name</th>#}
{#              <th scope="col">Description</th>#}
{#            </tr>#}
{#          </thead>#}
{#          <tbody>#}
{#            {% for project in projects %}#}
{#                <tr>#}
{#                    <th><a href="{% url "project:view" project.pk %}"> {{ project.name }}</th>#}
{#                    <th>{{ project.description_project }}</th>#}
{#                </tr>#}
{#            {% endfor %}#}
{#          {% include 'partial/paginate.html' %}#}
{#          </tbody>#}
{#        </table>#}


    {% include 'partial/project_list.html' %}

{% endblock content %}

hello/webapp/templates/project/project_create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
    {% include 'partial/form.html' with button_text='Создать' %}
</form>
{% endblock %}

hello/webapp/templates/project/project_delete.html
{% extends 'base.html' %}

{% block title %}Подтвердите удаление статьи{% endblock %}
{% block page_header %}Are u sure, to delete {{ project.name }}?{% endblock page_header %}

{% block content%}
    <form action="{% url "project:delete" project.id %}", method="POST">
        {% include 'partial/form.html' with button_text="Yes" %}
        <a href="{% url "project:view" project.id %}">Not</a>
    </form>
{% endblock content %}>

hello/webapp/templates/project/project_detail.html
{% extends "base.html" %}

{% block menu %}
    {% if perms.webapp.add_project %}
          <li><a href="{% url "project:add" %}">Create project</a></li>
    {% endif %}

    {% if perms.webapp.add_task %}
          <li><a href="{% url "project:add-task" project.pk %}">Create Task</a></li>
     {% endif %}

    {% if perms.webapp.view_project %}
          <li><a href="{% url "project:list" %}">List project</a></li>
    {% endif %}

    {% if perms.webapp.delete_project %}
          <li><a href="{% url "project:delete" project.id %}">Delete Project</a></li>
    {% endif %}

    {% if perms.webapp.update_project %}
          <li><a href="{% url "project:update" project.id %}">Update Project</a></li>
    {% endif %}

    {% if perms.webapp.have_user %}
          <li><a href="{% url "project:add-user" project.id %}">Add User</a></li>
    {% endif %}


{% endblock menu %}

{% block page_header %}Проект {{ project.id }}{% endblock page_header %}

{% block content %}
    <div class="card text-dark bg-info mb-3" style="max-width: 45rem;">
  <div class="card-header">Project</div>
  <div class="card-body">
    <p class="card-text">Name: {{ project.name}}</p>
    <p class="card-text">Description: {{ project.description_project }}</p>
    <p class="card-text">Start date: {{ project.start_date }}</p>
    <p class="card-text">End date: {{ project.end_date }}</p>
  </div>
</div>
    {% if not project.user.all %}
        <h2>No users</h2>
    {% endif %}
        {% for user in project.user.all %}
            <p><a href="{% url "accounts:user-detail" user.pk %}">{{ user.username }}</a></p>
        {% endfor %}


    {% if not project.tasks.all %}
        <h2>No trackers</h2>

    {% endif %}
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Id</th>
              <th scope="col">Summary</th>
              <th scope="col">Description</th>
            </tr>
          </thead>
          <tbody>
            {% for task in project.tasks.all %}
                <tr>
                    <th><a href="{% url "project:view-task" task.pk %}">{{ task.id }}</a></th>
                    <td>{{ task.summary }}</td>
                    <td>{{ task.description }}</td>
                </tr>
            {% endfor %}
          {% include 'partial/paginate.html' %}
          </tbody>
        </table>

{% endblock content %}

hello/webapp/templates/project/project_update.html
{% extends 'base.html' %}

{% block menu %}<li><a href="{% url "project:view" project.id %}">Back to project</a></li>{% endblock menu %}
{% block page_header %}Update project {{ project.id }}{% endblock page_header %}

{% block content %}
    <form action="{% url "project:update" project.id %}" method="post">
        {% include "partial/form.html" with button_text="update" %}
    </form>
{% endblock content %}