hello/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import register_view, UserDetailView, UserList, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('list/', UserList.as_view(), name='user-list'),
    path('profile/change/', UserChangeView.as_view(), name='user-change'),
    path('change-password/', UserPasswordChangeView.as_view(), name='user-password-change')
]

hello/hello/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

HOMEPAGE_URL = 'webapp/'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url=HOMEPAGE_URL, permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hello/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        on_delete=models.CASCADE,
        verbose_name='Профиль пользователя',
        related_name='profile'
    )
    bith_date = models.DateField(
      null=True,
      blank=True,
      verbose_name='Дата рождения'
    )

    avatar = models.ImageField(
       null=True,
       blank=True,
       upload_to='avatars',
       verbose_name='Аватар'
    )

    about_yourself = models.TextField(max_length=2900, null=True, blank=True, verbose_name='О себе')
    link = models.URLField(max_length=299, null=True, blank=True, verbose_name='Профиль на GitHub')

    def __str__(self):
        return self.user.username

    class Meta:
        db_table= 'profiles'
        verbose_name= 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'

hello/accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from accounts.models import Profile
from django.contrib.auth import get_user_model



class MyUserCreationForm(forms.ModelForm):
    password = forms.CharField(label="Пароль", strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", required=True, widget=forms.PasswordInput, strip=False)
    email = forms.CharField(required=True)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if not first_name and not last_name:
            raise forms.ValidationError('Заполните одно поле first_name или last_name!')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']

class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

class PasswordChangeForm(forms.ModelForm):
    new_password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        new_password = self.cleaned_data.get("new_password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if new_password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get("new_password"))
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['new_password', 'password_confirm', 'old_password']

hello/accounts/views.py
from django.shortcuts import render, redirect, reverse
from .forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from django.views.generic import DetailView, ListView, UpdateView
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.core.paginator import Paginator
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

from .models import Profile


def register_view(request, *args, **kwargs):
    context = {}
    form = MyUserCreationForm(data=request.POST)
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            return redirect('project:list')

    context['form'] = form
    return render(request, 'registration/user_create.html', context={'form': form})


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        projects = self.get_object().projects.all()
        paginator = Paginator(projects, self.paginate_related_by, orphans=self.paginate_related_orphans)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['projects'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class UserList(PermissionRequiredMixin, ListView):
    model = get_user_model()
    template_name = 'user_list.html'
    context_object_name = 'users'
    permission_required = 'auth.view_user'

class UserChangeView(LoginRequiredMixin,UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'usr_obj'
    profile_form_class = ProfileChangeForm

    def get_context_data(self, **kwargs):
        context = super(UserChangeView, self).get_context_data(**kwargs)
        context['profile_form'] = kwargs.get('profile_form')
        if context['profile_form'] is None:
            context['profile_form'] = self.get_profile_form()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        user_form = self.get_form()
        profile_form = self.get_profile_form()
        if user_form.is_valid() and profile_form.is_valid():
            return self.form_valid(user_form, profile_form)

    def get_object(self, queryset=None):
        return self.request.user

    def form_invalid(self, user_form, profile_form):
        context = self.get_context_data(
            form=user_form,
            profile_form=profile_form
        )
        return self.render_to_response(context)

    def form_valid(self, user_form, profile_form):
        response = super(UserChangeView, self).form_valid(user_form)
        profile_form.save()
        return response

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return self.profile_form_class(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:user-detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_success_url(self):
        return reverse('accounts:login')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        response = super(UserPasswordChangeView, self).form_valid(form)
        update_session_auth_hash(self.request, self.request.user)
        return response

    def get_success_url(self):
        return reverse('accounts:user-detail', kwargs={'pk': self.object.pk})

hello/accounts/templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

{% if has_error %}
    <div>Неправильный логин или пароль</div>
{% endif %}

<form action="{% url 'login' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username">
    <input type="text" name="password">
    <input type="submit">
</form>

</body>
</html>

hello/accounts/templates/password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}


{% block menu_links %}
    <li><a href="{% url "accounts:user-detail" user_obj.pk %}"></a>Назад</li>
    <li><a href="{% url "accounts:user-change" user_obj.pk%}"></a>редактирование личных данных</li>
{% endblock %}


{% block content %}
    <h1>Смена пароля</h1>
    <form action="" method="post">
    {% include 'partial/form.html' with button_text="change"  %}
    </form>
{% endblock %}

hello/accounts/templates/user_change.html
{% extends 'base.html' %}

{% block title %}Редактировать пользователя {% endblock %}

{% block menu_links %}
    <li><a href="{% url "accounts:user-detail" user_obj.pk %}"Назад></a></li>
    <li><a href="#">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <h1>Поменять личные данные</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {%  csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input type="submit" value="Submit">
        </form>
{% endblock %}

hello/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}Пользователь{% endblock %}

{% block menu %}
    {% if user == user_obj %}
        <li class="menu_right"><a href="{% url 'accounts:user-password-change' %}">Сменить пароль</a></li>
        <li class="menu_right"><a href="{% url 'accounts:user-change' %}">Редактировать профиль</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">

    {% endif %}
    <p>Имя пользователя: {{ user_obj.username }}</p>
    <p>Имя: {{ user_obj.first_name }}</p>
    <p>Фамилия: {{ user_obj.last_name }}</p>
    <p>Дата рождения: {{ user_obj.profile.bith_date|date:'d.m.Y' }}</p>
    <p>Почта: {{ user_obj.email }}</p>
    <p>Профиль на GitHub: {{ user_obj.profile.link }}</p>
    <p>О себе: {{ user_obj.profile.about_yourself }}</p>
    <h2 class="text-center clear">Проекты:</h2>
    {% include 'partial/project_list.html' %}
{% endblock %}

hello/accounts/templates/user_list.html
{% extends 'base.html' %}#}
{% block title %}Пользователь{% endblock %}

{% block content %}

    {% if not users%}
        <h2>No users</h2>
    {% endif %}
        {% for user in users %}
            <p><a href="{% url "accounts:user-detail" user.pk %}">{{ user.username }}</a></p>
        {% endfor %}

    {% endblock %}